[workspace]
git_release_enable = true
git_tag_enable     = true
changelog_path     = "CHANGELOG.md"

[[package]]
name = "cpufetch-rs"
# crates.io publishing handled by GHA release-plz action
publish = false
