# Basic formatting options
edition              = "2024"
style_edition        = "2024"
max_width            = 120
tab_spaces           = 4
hard_tabs            = false
newline_style        = "Unix"
use_small_heuristics = "Default"

# Import formatting
reorder_imports = true

# Code organization
reorder_modules            = true
match_block_trailing_comma = true
use_field_init_shorthand   = true
use_try_shorthand          = true
merge_derives              = true
