[target.'cfg(all())']
rustflags = [
    # Enable additional clippy lints
    "-Wclippy::all",
    "-Wclippy::pedantic",
    "-Aclippy::module_name_repetitions",
    "-Aclippy::too_many_lines",
]

[profile.release]
lto           = "thin"
codegen-units = 1
opt-level     = 3
debug         = false
strip         = "symbols"

[profile.dev]
opt-level = 1
debug     = true
